version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(deps)"
    assignees:
      - move-hoon
      - hyerinhwang-sailin
      - imddoy
