creation_rules:
  - path_regex: ^infra/ansible/inventories/dev/group_vars/all/.*\.sops\.yml$
    age: >-
      age10ku4fy9jalda7pkqwmgnywjnmeqdknv0fkt5a7dgs5egk9xf7atsa6vnpa,
      age1gagkvs6ur249muxexemtwumzqsvgpc74yxu7sfkhhsqyw7t8asesgsyyfn,
      age1gsw3fsp4m6shzrv9cvztagavxevzz3pdm9xdl9fk3mturkfzhc2qf4z67e
  - path_regex: ^infra/ansible/inventories/prod/group_vars/all/.*\.sops\.yml$
    age: >-
      age10ku4fy9jalda7pkqwmgnywjnmeqdknv0fkt5a7dgs5egk9xf7atsa6vnpa,
      age1gagkvs6ur249muxexemtwumzqsvgpc74yxu7sfkhhsqyw7t8asesgsyyfn,
      age1gsw3fsp4m6shzrv9cvztagavxevzz3pdm9xdl9fk3mturkfzhc2qf4z67e
