package com.beat.apps.api.booking.web

const val BOOKING_API_PATH = "/api/bookings"
const val GUEST_BOOKING_REFUND_ROUTE = "/refund"
const val GUEST_BOOKING_CANCEL_ROUTE = "/cancel"
const val GUEST_BOOKING_REFUND_PATH = "$BOOKING_API_PATH$GUEST_BOOKING_REFUND_ROUTE"
const val GUEST_BOOKING_CANCEL_PATH = "$BOOKING_API_PATH$GUEST_BOOKING_CANCEL_ROUTE"

val GUEST_BOOKING_MUTATION_PATHS = setOf(GUEST_BOOKING_REFUND_PATH, GUEST_BOOKING_CANCEL_PATH)
