---
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
      password: ${DEV_REDIS_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}
      password: ${PROD_REDIS_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: localhost
      port: 6379
      password:
