server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  data:
    redis:
      host: beat-dev-redis
      port: 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${DEV_KAKAO_CLIENT_ID}
            client-secret: ${DEV_KAKAO_CLIENT_SECRET}
            redirect-uri: ${DEV_KAKAO_REDIRECT_URI}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  coolsms:
    api:
      key: ${DEV_COOLSMS_KEY}
      secret: ${DEV_COOLSMS_SECRET}
      number: ${DEV_COOLSMS_NUMBER}

jwt:
  secret: ${DEV_JWT_SECRET}
  access-token-expire-time: 31536000000 # 365일 (1년) 밀리초
  refresh-token-expire-time: 1209600000 # 14일 밀리초

cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access-key: ${DEV_S3_ACCESS_KEY}
      secret-key: ${DEV_S3_SECRET_KEY}
  s3:
    bucket: beat-dev-bucket
  stack:
    auto: false

