spring:
  config:
    import: optional:classpath:application-secret.properties
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: com.beat.global.common.config.MysqlCustomDialect
        format_sql: true

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
      password: ${DEV_REDIS_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${DEV_KAKAO_CLIENT_ID}
            client-secret: ${DEV_KAKAO_CLIENT_SECRET}
            redirect-uri: ${DEV_KAKAO_REDIRECT_URI}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  coolsms:
    api:
      key: ${DEV_COOLSMS_KEY}
      secret: ${DEV_COOLSMS_SECRET}
      number: ${DEV_COOLSMS_NUMBER}

server:
  port: 8080

management:
  server:
    port: ${DEV_ACTUATOR_PORT}
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: info, health, prometheus
      base-path: ${DEV_ACTUATOR_PATH}
  prometheus:
    metrics:
      export:
        enabled: true

jwt:
  secret: ${DEV_JWT_SECRET}
  access-token-expire-time: ${DEV_ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token-expire-time: ${DEV_REFRESH_TOKEN_EXPIRE_TIME}

cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access-key: ${DEV_S3_ACCESS_KEY}
      secret-key: ${DEV_S3_SECRET_KEY}
  s3:
    bucket: beat-dev-bucket
  stack:
    auto: false

logging:
  level:
    root: info
  config: classpath:log4j2-spring.xml


cors:
  allowed-origins: ${DEV_ALLOWED_ORIGINS}

app:
  server:
    url: ${DEV_SERVER_URL}

springdoc:
  use-fqn: false
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    urls-primary-name: general

slack:
  webhook:
    url: ${DEV_SLACK_WEBHOOK_URL}

thread-pool:
  core-size: 2
  thread-name-prefix: executor-
