all:
  vars:
    ansible_port: 22
    ansible_user: ubuntu
  children:
    apis_servers:
      hosts:
        dev-server:
    admin_servers:
      hosts:
        dev-server:
    batch_servers:
      hosts:
        dev-server:
