---
- name: Ensure secret directory exists
  ansible.builtin.file:
    path: "{{ secret_dir }}"
    state: directory
    owner: root
    group: "10001"
    mode: "0750"

- name: Write profile secret properties
  ansible.builtin.template:
    src: application-secret.properties.j2
    dest: "{{ secret_dir }}/application-{{ module_cfg.spring_profile }}-secret.properties"
    owner: root
    group: "10001"
    mode: "0640"
  no_log: true
