---
- name: Sync application secret only
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: app_secret
      vars:
        app_secret_module_cfg:
          spring_profile: "{{ deploy_environment }}"
      tags:
        - secret
