---
- name: Sync application secret only
  hosts: all
  become: true
  gather_facts: false
  vars:
    module_cfg:
      spring_profile: "{{ deploy_environment }}"

  roles:
    - role: app_secret
      tags:
        - secret
